backend:
  name: git-gateway
  branch: main # Asegúrate de que sea la rama de tu GitHub

local_backend: true

media_folder: "imagenes" # Carpeta donde se guardarán las fotos del blog
public_folder: "imagenes"

collections:
  - name: "blog"
    label: "Entradas del Blog"
    folder: "blog" # Aquí se guardarán los archivos de texto automáticos
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Título de la Nota", name: "title", widget: "string" }
      - { label: "Fecha de Publicación", name: "date", widget: "string" }
      - { label: "Resumen Corto", name: "description", widget: "text" }
      - { label: "Imagen Destacada", name: "image", widget: "image" }
      - { label: "Cuerpo del Artículo", name: "body", widget: "markdown" }